# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iNxshRlvyev0GKV2EeyysKbeXpVETpwQ
"""

import pandas as pd
teacher=pd.DataFrame([
    "FISH":["QADAMOVA.Z.E","Djalilov.M.L", "Burhonova.M.M" ,"Xontorayev.S.I" ,"Arabboyev.A.A"   ],
    "fan nomi":["suniy intelekt asoslari","Kompyuterni tashkil etish","kompyuterni tashkil etish","malumotlar tuzilmasi va algoritmlar"},
    "MASHGULOT TURI":["AMALIY"     ],
  "DARS OTISH MAHORATI":["A'LO"  ],
])
print(teacher)

teacher.to_excel("teacher.xlsx")